class Strings {
  // static String baseUrl = "https://mimidating.com/opulencia";
  // static String baseUrl = "https://test.anna-reddy.co.in/opulencia";
  static String baseUrl = "https://updatesbyrobolaxy.com/opulencia";
  static String appFont = "Outfit";
  static String dummyProfile =
      "https://media.istockphoto.com/id/1393750072/vector/flat-white-icon-man-for-web-design-silhouette-flat-illustration-vector-illustration-stock.jpg?s=612x612&w=0&k=20&c=s9hO4SpyvrDIfELozPpiB_WtzQV9KhoMUP9R9gVohoU=";
  static String title = "title";
  static String login = "login";
  static String phoneNumber = "phoneNumber";
  static String sendOtp = "sendOtp";
  static String or = "or";
  static String next = "next";
  static String codeSent = "codeSent";
  static String verificationCode = "verificationCode";
  static String codeNotRecieved = "codeNotRecieved";
  static String resend = "resend";
  static String wishlist = 'wishlist';
  static String orders = 'orders';
  static String profileInfo = 'profileInfo';
  static String favorites = 'favorites';
  static String tellFriend = 'tellFriend';
  static String settings = 'settings';
  static String customOrder = 'customOrder';
  static String logout = 'logout';
  static String home = 'home';
  static String explore = 'explore';
  static String profile = 'profile';
  static String trendingFrames = 'trendingFrames';
  static String exploreByCategory = "exploreByCategory";
  static String newInMarket = "newInMarket";
  static String myAddresses = "myAddresses";
  static String frameColor = "frameColor";
  static String size = "size";
  static String description = "description";
  static String addToCart = "addToCart";
  static String orderNow = "orderNow";
  static String currency = "AOA";
}
